name: Greetings

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: 'Salam @${{ github.actor }} , thank you for submitting an issue to Open Science Community Saudi Arabia (OSCSA)'
        pr-message: 'Salam @${{ github.actor }} , thank you submitting a pull request to Open Science Community Saudi Arabia (OSCSA).'
